spring.application.name=localloop-backend

# ?? AIVEN CLOUD DATABASE CONNECTION ??
spring.datasource.url=jdbc:mysql://mysql-39ea1d4d-bokkachandravamsi68-7767.a.aivencloud.com:15253/defaultdb?sslMode=REQUIRED
spring.datasource.username=avnadmin
spring.datasource.password=${DB_PASSWORD}

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# ?? HIBERNATE SETTINGS ??
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

# ?? CLOUD PORT BINDING (Needed for Render later) ??
server.port=${PORT:8080}